---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress-server
  # remote_user: root
  remote_user: plarsen
  sudo: yes

  tasks:
  - name: Install firewalld
    yum:
      name: "firewalld"
      state: present
      
  - name: stoart firewalld
    service: 
      name: firewalld 
      state: started

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
