---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: wordpress-server
  # remote_user: root
  remote_user: plarsen
  sudo: yes
  
- name: Install firewalld
  yum: name="firewalld" state=present

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
